steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - gcloud
      - artifacts
      - generic
      - download
      - '--project=cmoc-prod'
      - '--location=us'
      - '--repository=codemender-cli-production'
      - '--package=cm'
      - '--version=stable'
      - '--name=cm-linux-amd64.zip'
      - '--destination=./'
  - name: ubuntu
    args:
      - '-c'
      - |
        apt-get update
        apt-get install -y ca-certificates
        apt-get install -y unzip
        unzip cm-linux-amd64.zip
        chmod +x cm
        ./cm init
        ./cm find routes/login.ts
    entrypoint: bash    
  - name: ubuntu
    args:
      - '-c'
      - |      
        client_id='Iv23licJdfOKFpy5vsNt'

        pem=$$CODEMENDER_GITHUB_APP_PRIVATE_KEY
        echo -n "${pem}"

        now=$(date +%s)
        iat=$((${now} - 60)) # Issues 60 seconds in the past
        exp=$((${now} + 600)) # Expires 10 minutes in the future

        b64enc() { openssl base64 | tr -d '=' | tr '/+' '_-' | tr -d '\n'; }

        header_json='{
            "typ":"JWT",
            "alg":"RS256"
        }'
        # Header encode
        header=$( echo -n "${header_json}" | b64enc )

        payload_json="{
            \"iat\":${iat},
            \"exp\":${exp},
            \"iss\":\"${client_id}\"
        }"
        # Payload encode
        payload=$( echo -n "${payload_json}" | b64enc )

        # Signature
        header_payload="${header}"."${payload}"
        signature=$(
            openssl dgst -sha256 -sign <(echo -n "${pem}") \
            <(echo -n "${header_payload}") | b64enc
        )

        # Create JWT
        "${header_payload}"."${signature}" >> jwt.txt        
    entrypoint: bash  
    secrets: ['CODEMENDER_GITHUB_APP_PRIVATE_KEY']  
  - name: ubuntu
    args:
      - '-c'
      - |      
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $( cat jwt.txt )" \
        -H "X-GitHub-Api-Version: 2026-03-10" \
        https://api.github.com/repos/ryanmcgrail/juice-shop/pulls \
        -d '{"title":"Test pull request","body":"Please pull these awesome changes in!","base":"master"}'
    entrypoint: bash
options:
  logging: CLOUD_LOGGING_ONLY
availableSecrets:
  secretManager:
  - versionName: projects/test-project-502314/secrets/codemender-github-app-private-key/versions/1
    env: 'CODEMENDER_GITHUB_APP_PRIVATE_KEY'

