steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - gcloud
      - artifacts
      - generic
      - download
      - '--project=cmoc-prod'
      - '--location=us'
      - '--repository=codemender-cli-production'
      - '--package=cm'
      - '--version=stable'
      - '--name=cm-linux-amd64.zip'
      - '--destination=./'
  - name: ubuntu
    args:
      - '-c'
      - |
        apt-get update
        apt-get install -y ca-certificates
        apt-get install -y unzip
        unzip cm-linux-amd64.zip
        chmod +x cm
        ./cm init
        ./cm find routes/login.ts
    entrypoint: bash    
  - name: ubuntu
    args:
      - '-c'
      - |
        apt-get update
        apt-get install -y openssl curl

        client_id='Iv23licJdfOKFpy5vsNt'
        pem=$$CODEMENDER_GITHUB_APP_PRIVATE_KEY

        now=$(date +%s)
        iat=$((${now} - 30)) # Issues 30 seconds in the past
        exp=$((${now} + 600)) # Expires 10 minutes in the future

        b64enc() { openssl base64 | tr -d '=' | tr '/+' '_-' | tr -d '\n'; }

        header_json='{
            "typ":"JWT",
            "alg":"RS256"
        }'

        # Header encode
        header=$( echo -n "${header_json}" | b64enc )

        payload_json="{
            \"iat\":${iat},
            \"exp\":${exp},
            \"iss\":\"${client_id}\"
        }"

        # Payload encode
        payload=$( echo -n "${payload_json}" | b64enc )

        # Signature
        header_payload="${header}"."${payload}"
        signature=$(
            openssl dgst -sha256 -sign <(echo -n "${pem}") \
            <(echo -n "${header_payload}") | b64enc
        )

        # Create JWT
        jwt="${header_payload}"."${signature}" >> jwt.txt
        echo "${jwt}" > jwt.txt
    entrypoint: bash
    secretEnv:
      - CODEMENDER_GITHUB_APP_PRIVATE_KEY
  - name: ubuntu
    args:
      - '-c'
      - >
        apt-get update

        apt-get install -y curl

        echo "curling for installations"

        jwt=$(cat jwt.txt)

        installations_response=$(curl -i \
          -H "Authorization: Bearer ${jwt}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/app/installations)

        installation_id=$(echo "${installations_response}" | grep -m 1 "\"id\":"
        | sed -nE 's/\s*"id": ([0-9]+),/\1/p')

        installation_token_response=$(curl --request POST \
          --url "https://api.github.com/app/installations/${installation_id}/access_tokens" \
          --header "Accept: application/vnd.github+json" \
          --header "Authorization: Bearer ${jwt}" \
          --header "X-GitHub-Api-Version: 2026-03-10")

        installation_token=$(echo "${installation_token_response}" | grep
        "\"token\":" | sed -nE 's/\s*"token": "(.*)",/\1/p')

        echo "${installation_token}" > installation_token.jwt
    entrypoint: bash
  - name: ubuntu
    args:
      - '-c'
      - >
        apt-get update

        apt-get install -y curl

        jwt=$(cat installation_token.jwt) 

        curl -L -X GET H "Accept: application/vnd.github+json" -H
        "Authorization: Bearer ${jwt}" -H "X-GitHub-Api-Version: 2026-03-10" 

        curl -L -X POST -H "Accept: application/vnd.github+json" -H
        "Authorization: Bearer ${jwt}" -H "X-GitHub-Api-Version: 2026-03-10"
        https://api.github.com/repos/ryanmcgrail/juice-shop/pulls  -d
        '{"title":"Test pull request","body":"Please pull these awesome  changes
        in!","base":"master"}'
    entrypoint: bash
options:
  logging: CLOUD_LOGGING_ONLY
availableSecrets:
  secretManager:
    - versionName: >-
        projects/test-project-502314/secrets/codemender-github-app-private-key/versions/1
      env: CODEMENDER_GITHUB_APP_PRIVATE_KEY
